### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by JB-GB** [brucemack/Tachometer#2]
Hi! I'm interested on replicate this on a CH440 of kohler but I'm having some trouble making it work.
---
### Parts replaced:
- 2N3906 with a 2N4401
- BAT54S with 2 zener diodes of 12v 1W
- Took 3.3v and GND from arduino
--- 
I've done this on a breadboard...
![image](https://github.com/user-attachments/assets/6e4a32d6-abb8-4b76-9028-99ca1fd011ad)
#### HOWEVER
When I run the code and start the serial monitor, the ```maxMag``` variable starts sending numbres like 84, 95, 124. (engine not running). Not just that, but when I start it, the arduino disconects the serial monitor. I suppose this may be an issue with current flow or something similar. I flashed another program just to verify the integrity of my arduino UNO, and looks fine so far, but I've no idea what's the matter. Should I not ignore the black cable connected to engine block? Can I even use the power provided from the same arduino?

**Comment by brucemack** [comment]
Your circuit looks reasonable at first glance.
Yes, you can take the 3.3V from the Arduino.
The black wire going to the engine block should be attached to the ground of your Arduino.
When you say that the serial monitor connection disconnects when you "start it," can you be more specific about what you are starting exactly?

**Comment by JB-GB** [comment]
Yes, it's more like it suddenly stops monitoring (seems like has been disconnected) when engine start running. I acquire the exact components you include in the diagram, in any case, keeps doing the same. A partner may send some video evidence later on at this thread.
